// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkkpldTshloKEodWFdMGHBFjYHGlUv0Ak',
    appId: '1:26732554565:web:12289a540dd2972d7c762c',
    messagingSenderId: '26732554565',
    projectId: 'guarana-balu',
    authDomain: 'guarana-balu.firebaseapp.com',
    storageBucket: 'guarana-balu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxzwYj539F-1pAvPbp0PPj2-d7xvppob8',
    appId: '1:26732554565:android:865a6af8fa8191cc7c762c',
    messagingSenderId: '26732554565',
    projectId: 'guarana-balu',
    storageBucket: 'guarana-balu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMgSOSPTtLyuqbiEWpmwWQpZDoTM2F7E',
    appId: '1:26732554565:ios:19b4f6510f928fae7c762c',
    messagingSenderId: '26732554565',
    projectId: 'guarana-balu',
    storageBucket: 'guarana-balu.appspot.com',
    iosClientId: '26732554565-nfjk03ghs6tdm9pia1lkbfhergvasmdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.guaranaMania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMgSOSPTtLyuqbiEWpmwWQpZDoTM2F7E',
    appId: '1:26732554565:ios:19b4f6510f928fae7c762c',
    messagingSenderId: '26732554565',
    projectId: 'guarana-balu',
    storageBucket: 'guarana-balu.appspot.com',
    iosClientId: '26732554565-nfjk03ghs6tdm9pia1lkbfhergvasmdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.guaranaMania',
  );
}
